image: ubuntu:latest

deploy_production:
  only:
    refs:
      - master
  cache: {}
  stage: deploy
  environment:
    name: Production
    url: https://nextjs-typescript-chakraui.techsavagery.net
  script:
    - apt-get update -qq && apt-get install -y -qq sshpass
    - sshpass -V
    - export SSHPASS=$USER_PASS
    - script -qc "sshpass -p $USER_PASS ssh $USER_NAME@$SERVER_IP cd ~"
    - script -qc "sshpass -p $USER_PASS ssh $USER_NAME@$SERVER_IP cd nextjs-typescript-chakraui"
    - script -qc "sshpass -p $USER_PASS ssh $USER_NAME@$SERVER_IP git pull"
    - script -qc "sshpass -p $USER_PASS ssh $USER_NAME@$SERVER_IP npm install"
    - script -qc "sshpass -p $USER_PASS ssh $USER_NAME@$SERVER_IP npm run build"
    - script -qc "sshpass -p $USER_PASS ssh $USER_NAME@$SERVER_IP pm2 restart nextjs-typescript-chakraui"
